{% extends "variants/essentials/Dockerfile.base.sh.twig" %}



{% block application_mysql %}
{% include 'template/components/maria-db/10.3/install.sh.twig' with { 'pwd' : db.pwd } %}

&& service mysql start \
    && mysql --user={{ db.user }} --password={{ db.pwd }} -e "use mysql; update user set host='%' where host='localhost';" \
    && service mysql restart \
{% endblock %}