{% extends "template/Dockerfile.global.sh.twig" %}

{% block docker_from %}
FROM dockware/essentials:latest
{% endblock %}

{% block basic_variables %}{% endblock %}
{% block main_os %}{% endblock %}

{% block application %}
{% block assets_install_shopware6 %}
&& echo ""
COPY ./assets/shopware6/files /var/www/scripts/shopware6
RUN echo "" \
{% endblock %}

{% block shopware %}

{% block shopware_install %}
## ***********************************************************************
##  INSTALL SHOPWARE
## ***********************************************************************
    && rm -rf /var/www/html/* \
    && wget {{ shopware.download_url }} -qq -O /var/www/shopware.zip \
    && sudo -u www-data sh -c 'unzip -q /var/www/shopware.zip -d /var/www/html' \
    && rm -rf /var/www/shopware.zip \
{% endblock %}

{% block shopware_prepare %}

{% block shopware_prepare_env %}
    && echo "APP_ENV={{ shopware.env }}" >> /var/www/html/.env && \
    echo "APP_SECRET=1" >> /var/www/html/.env && \
    echo "INSTANCE_ID=1" >> /var/www/html/.env && \
    echo "DATABASE_URL=mysql://{{ db.user }}:{{ db.pwd }}@{{ db.host }}:{{ db.port }}/{{ db.database }}" >> /var/www/html/.env && \
    echo "APP_URL={{ shopware.url }}" >> /var/www/html/.env && \
    echo "MAILER_URL=smtp://localhost:1025" >> /var/www/html/.env && \
    echo "COMPOSER_HOME=/var/www/html/var/cache/composer" >> /var/www/html/.env && \
    echo "SHOPWARE_ES_ENABLED=0" >> /var/www/html/.env && \
    chown www-data:www-data /var/www/html/.env \
{% endblock %}


    && service mysql start \
    # switch to default PHP before installing
    && sudo update-alternatives --set php /usr/bin/php{{ php.default_version }} > /dev/null 2>&1 && \
    cd /var/www/html && sudo -u www-data sh -c 'php bin/console system:install --create-database --basic-setup' && \
    # make sure assets like logos are ready
    cd /var/www/html && sudo -u www-data sh -c 'php bin/console assets:install' && \
    # add some demo data
    {% if version_gte(shopware.version, '6.2.0-rc1') %}
    cd /var/www/html && sudo -u www-data sh -c 'APP_ENV=prod php bin/console store:download -p SwagPlatformDemoData' && \
    cd /var/www/html && sudo -u www-data sh -c 'APP_ENV=prod php bin/console plugin:refresh' && \
    cd /var/www/html && sudo -u www-data sh -c 'APP_ENV=prod php bin/console plugin:install --activate SwagPlatformDemoData' && \
    {% else %}
    cd /var/www/html && sudo -u www-data sh -c 'APP_ENV=prod php bin/console framework:demodata' && \
    {% endif %}
    # clear cache and refresh dal index to show the new demo data
    cd /var/www/html && sudo -u www-data sh -c 'php bin/console cache:clear' && \
    cd /var/www/html && sudo -u www-data sh -c 'php bin/console dal:refresh:index' && \
    rm -rf /var/www/html/var/cache/* && \
    mysql --user={{ db.user }} --password={{ db.pwd }} -e "use {{ db.database }}; INSERT INTO system_config (id, configuration_key, configuration_value, sales_channel_id, created_at, updated_at) VALUES (X'b3ae4d7111114377af9480c4a0911111', 'core.frw.completedAt', '{\"_value\": \"2019-10-07T10:46:23+00:00\"}', NULL, '2019-10-07 10:46:23.169', NULL);" && \
    service mysql stop \
{% endblock %}

{% block shopware_dev %}{% endblock %}

# sometimes there are permission problems
# so make sure to assign them correctly again here
    && chown -R www-data:www-data /var/www/html && \
    chmod -R 775 /var/www/html && \
    cd /var/www/scripts/shopware6 && php create_jwt.php && \
    cd /var/www/html/config/jwt && chown www-data:www-data * \
{% endblock %}

{% endblock %}

